### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by dimmonn** [kamer/spring-boot-user-registration#1]
`The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  webConfig defined in file [WebConfig.class]
↑     ↓
|  userService defined in file [UserService.class]
└─────┘`

**Comment by KenobySky** [comment]
Having the same issue. And since Im new with spring boot, I have no idea on how to fix it.

**Comment by dimmonn** [comment]
You should avoid circular dependenciesdimaOn Sep 5, 2020 7:30 PM, KenobiShan <notifications@github.com> wrote:
Having the same issue. And since Im new with spring boot, I have no idea on how to fix it.

**Comment by KenobySky** [comment]
I dont know how to fix it. Sorry.

**Comment by kamer** [comment]
@KenobySky  @dimmonn Thanks for pointing out that issue. I've just fixed it.
